name: Build otoge binaries

on:
  pull_request:
    paths:
      - "**"
      - "!data/**"
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!data/**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install rust toolchain
        run: cargo version

      - name: Cache rust artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: build
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build otoge
        run: cargo build --release
